### ISSUE TITLE
Readme example conflicts with "read-only" clause in spec

### ISSUE THREAD

**Issue by airstruck** [bartbes/Class-Commons#7]
From the spec:

> A class SHOULD be considered read-only after having been passed to common.class.

This example in the readme conflicts with that:

    foo = common.class("foo", {})
    function foo:init()
        self.bar = "baz"
    end

Suggested fix:

    local foo = {}
    function foo:init()
        self.bar = "baz"
    end
    foo = common.class("foo", foo)

**Comment by bartbes** [comment]
I think we added that condition after I wrote the example, good spot.

**Comment by airstruck** [comment]
FWIW, I think it's a good condition to have. In my particular situation retroactively adding `init` is the only case where modifying a class after calling `common.class` wouldn't work properly, but having to support it would be a mess.

I'm curious if it's the same for the other class libraries implementing class commons. If so, it might be worth removing the read-only condition and handling constructors another way, like passng a string to `common.class` with the name of the constructor (in a future version of the spec, of course).

**Comment by bartbes** [comment]
I'm fairly sure that, at least when we drafted the specification, someone specifically requested this because it would be messy. To me only the constructor comes to mind as well, but the spec technically also allows libraries that aren't __index based, so it can be a tricky thing in general.

**Comment by bartbes** [comment]
Just updated the readme, thanks for reporting.
